#!/bin/zsh
#
# This lets you quickly jump into a project directory.
#
# Type:
#
#   c <tab>
#
# ...to autocomplete on all of your projects in the directories specified in
# `functions/_c`. Typically I'm using it like:
#
#    c holm<tab>/bo<tab>
#
# ...to quickly jump into holman/boom, for example.

if [ ! -z "$1" ] && [ -s "$GOPATH/src/github.com/nonoesp/$1" ]; then
  cd "$GOPATH/src/github.com/nonoesp/$1"
elif [ ! -z "$1" ] && [ -s "$PROJECTS/$1" ]; then
 cd "$PROJECTS/$1"
elif [ ! -z "$1" ] && [ -s "$LIBRARY/$1" ]; then
 cd "$LIBRARY/$1"
elif [ ! -z "$1" ] && [ -s "$INBOX/$1" ]; then
 cd "$INBOX/$1"
elif [ ! -z "$1" ] && [ -s "$WEB/$1" ]; then
 cd "$WEB/$1"
elif [ ! -z "$1" ] && [ -s "$GITHUB_NONOESP/$1" ]; then
 cd "$GITHUB_NONOESP/$1"
elif [ ! -z "$1" ] && [ -s "$BITBUCKET_NONOESP/$1" ]; then
 cd "$BITBUCKET_NONOESP/$1"
else
  cd "$PROJECTS/$1"
fi
