#!/bin/sh
#
# Smart mkdir.
# Creates and enters a directory.

function mkd() {
    if [ -z "$1" ]; then
        echo "Usage: mkd <directory_name>"
        return 1
    fi

    mkdir -p "$1"
    cd "$1"
}